//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demizon.Mvc.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DemizonLocales {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DemizonLocales() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Demizon.Mvc.Locales.DemizonLocales", typeof(DemizonLocales).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        internal static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folk ensemble Demižón was founded in 1999 and from the very beginning we have been working under the Orel association in Strážnice. Our members are between 16 and 28 years old – we currently have 13 dancing couples accompanied by cimbalom music..
        /// </summary>
        internal static string AboutUsText1 {
            get {
                return ResourceManager.GetString("AboutUsText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our repertoire consists mainly of songs and dances from Strážnice and its surroundings, but we also occasionally draw from Slovakia to add variety to our programme..
        /// </summary>
        internal static string AboutUsText2 {
            get {
                return ResourceManager.GetString("AboutUsText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        internal static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance.
        /// </summary>
        internal static string Attendance {
            get {
                return ResourceManager.GetString("Attendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attends.
        /// </summary>
        internal static string Attends {
            get {
                return ResourceManager.GetString("Attends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthdate.
        /// </summary>
        internal static string Birthdate {
            get {
                return ResourceManager.GetString("Birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Come to rehearsal.
        /// </summary>
        internal static string ComeToRehearsal {
            get {
                return ResourceManager.GetString("ComeToRehearsal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interested in a performance or collaboration? Don&apos;t hesitate to contact us..
        /// </summary>
        internal static string ContactSubtitle {
            get {
                return ResourceManager.GetString("ContactSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or all contacts.
        /// </summary>
        internal static string ContactUsButton {
            get {
                return ResourceManager.GetString("ContactUsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dance.
        /// </summary>
        internal static string Dance {
            get {
                return ResourceManager.GetString("Dance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dances.
        /// </summary>
        internal static string Dances {
            get {
                return ResourceManager.GetString("Dances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repertoire will be added soon..
        /// </summary>
        internal static string DancesEmpty {
            get {
                return ResourceManager.GetString("DancesEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repertoire of folk ensemble Demižón from Strážnice.
        /// </summary>
        internal static string DancesSubtitle {
            get {
                return ResourceManager.GetString("DancesSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete item?.
        /// </summary>
        internal static string DeleteItem {
            get {
                return ResourceManager.GetString("DeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English/Deutsch contact.
        /// </summary>
        internal static string EnglishAndGermanCommunicationText {
            get {
                return ResourceManager.GetString("EnglishAndGermanCommunicationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensemble leader.
        /// </summary>
        internal static string EnsembleLeader {
            get {
                return ResourceManager.GetString("EnsembleLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        internal static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        internal static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Schedule.
        /// </summary>
        internal static string EventSchedule {
            get {
                return ResourceManager.GetString("EventSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where you can see us.
        /// </summary>
        internal static string EventsSubtitle {
            get {
                return ResourceManager.GetString("EventsSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every Friday evening.
        /// </summary>
        internal static string EveryFridayEvening {
            get {
                return ResourceManager.GetString("EveryFridayEvening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firstname.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form.
        /// </summary>
        internal static string Form {
            get {
                return ResourceManager.GetString("Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folk ensemble from Strážnice.
        /// </summary>
        internal static string HeroSubtitle {
            get {
                return ResourceManager.GetString("HeroSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Login or Password.
        /// </summary>
        internal static string InvalidSignIn {
            get {
                return ResourceManager.GetString("InvalidSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is visible.
        /// </summary>
        internal static string IsVisible {
            get {
                return ResourceManager.GetString("IsVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Us.
        /// </summary>
        internal static string JoinUs {
            get {
                return ResourceManager.GetString("JoinUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Come see us or join us!.
        /// </summary>
        internal static string JoinUsCta {
            get {
                return ResourceManager.GetString("JoinUsCta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for new dancers and musicians – regardless of age and experience.
        /// </summary>
        internal static string JoinUsSubtitle {
            get {
                return ResourceManager.GetString("JoinUsSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to learn to dance – whether yourself or someone you know – just get in touch or come straight to rehearsal on Friday!.
        /// </summary>
        internal static string JoinUsText1 {
            get {
                return ResourceManager.GetString("JoinUsText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We dance many different dances from Moravia and Slovakia, so no one will ever be bored. We look forward to meeting you!.
        /// </summary>
        internal static string JoinUsText2 {
            get {
                return ResourceManager.GetString("JoinUsText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member.
        /// </summary>
        internal static string Member {
            get {
                return ResourceManager.GetString("Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        internal static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member since.
        /// </summary>
        internal static string MemberSince {
            get {
                return ResourceManager.GetString("MemberSince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Men.
        /// </summary>
        internal static string Men {
            get {
                return ResourceManager.GetString("Men", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No members to display..
        /// </summary>
        internal static string NoMembersToDisplay {
            get {
                return ResourceManager.GetString("NoMembersToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our calendar is free at the moment..
        /// </summary>
        internal static string NoUpcomingEventsPageHeader {
            get {
                return ResourceManager.GetString("NoUpcomingEventsPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow us on social media and you&apos;ll be the first to know about our upcoming events — or get in touch if you&apos;d like us to perform at your event!.
        /// </summary>
        internal static string NoUpcomingEventsPageText {
            get {
                return ResourceManager.GetString("NoUpcomingEventsPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or reach us online.
        /// </summary>
        internal static string OrContactUs {
            get {
                return ResourceManager.GetString("OrContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        internal static string Photos {
            get {
                return ResourceManager.GetString("Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo gallery will be added soon..
        /// </summary>
        internal static string PhotosEmpty {
            get {
                return ResourceManager.GetString("PhotosEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos from ensemble life.
        /// </summary>
        internal static string PhotosSubtitle {
            get {
                return ResourceManager.GetString("PhotosSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        internal static string Place {
            get {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home - public.
        /// </summary>
        internal static string PublicHome {
            get {
                return ResourceManager.GetString("PublicHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repertoire.
        /// </summary>
        internal static string Repertoire {
            get {
                return ResourceManager.GetString("Repertoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        internal static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming events.
        /// </summary>
        internal static string UpcomingEvents {
            get {
                return ResourceManager.GetString("UpcomingEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        internal static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload profile photo.
        /// </summary>
        internal static string UploadProfilePhoto {
            get {
                return ResourceManager.GetString("UploadProfilePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Instagram or Facebook.
        /// </summary>
        internal static string ViaContactPage {
            get {
                return ResourceManager.GetString("ViaContactPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Link.
        /// </summary>
        internal static string VideoLink {
            get {
                return ResourceManager.GetString("VideoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Links.
        /// </summary>
        internal static string VideoLinks {
            get {
                return ResourceManager.GetString("VideoLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        internal static string Videos {
            get {
                return ResourceManager.GetString("Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No videos to display..
        /// </summary>
        internal static string VideosEmpty {
            get {
                return ResourceManager.GetString("VideosEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recordings from performances.
        /// </summary>
        internal static string VideosSubtitle {
            get {
                return ResourceManager.GetString("VideosSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When.
        /// </summary>
        internal static string When {
            get {
                return ResourceManager.GetString("When", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why &apos;Demižón&apos;?.
        /// </summary>
        internal static string WhyDemizon {
            get {
                return ResourceManager.GetString("WhyDemizon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many people pause at this name – and that always reassures us that we have made our mark on another person&apos;s memory..
        /// </summary>
        internal static string WhyDemizonText1 {
            get {
                return ResourceManager.GetString("WhyDemizonText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A winemaker places the result of their year&apos;s work into a demijohn and lets it mature into its finest form. The same goes for the members of folk ensemble Demižón – a year&apos;s work and effort matures into a beautiful performance..
        /// </summary>
        internal static string WhyDemizonText2 {
            get {
                return ResourceManager.GetString("WhyDemizonText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And the maturing of dancers and musicians? Like wine – the older, the better. But it requires constant care!.
        /// </summary>
        internal static string WhyDemizonText3 {
            get {
                return ResourceManager.GetString("WhyDemizonText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Women.
        /// </summary>
        internal static string Women {
            get {
                return ResourceManager.GetString("Women", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
